### ISSUE TITLE
Use platform-specific trash folder

### ISSUE THREAD

**Issue by lewisfm** [spicylemonade/punch#11]
Currently, punch uses its own trash folder in `~/.punch/trash/`. In order to feel like a more native experience on platforms with their own trash, and to have better interoperability with other CLI tools, I’d like to suggest using the platform-specific trash folder. On most Linux distros, this is `~/.local/share/Trash/`, on macOS this is `~/.Trash/`, and I’m not sure what it is on Windows (maybe a hidden directory in the home folder).

**Comment by lewisfm** [comment]
I’ve found an trash folder spec for Linux distros, but I’m not sure how many follow this: https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html

**Comment by spicylemonade** [comment]
I thought about that, but I saw the trash feature as something extra where you can keep files in case you arent really sure if youl still need. This is also makes it easier for the database to track where files are.
